### PR TITLE
Update for 1.12.1

### PR DESCRIPTION
**Pull request by JakeMoe**
I've updated the files to make this work with 1.12.1.  Hope this helps.  Let me know if you'd like anything changed.

### CODE REVIEW

**Comment by konnkiti** [comment]
An error occurred when trying to build with Maven 3.
Please tell me how to resolve.
[ERROR] Failed to execute goal on project mcMMO-WorldGuard: Could not resolve dependencies for project org.mcmmo:mcMMO-WorldGuard:jar:1.0.4: Failure to find com.gmail.nossr50.mcMMO:mcMMO:jar:1.5.08.204 in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of spigot-repo has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by JakeMoe** [comment]
Did you download the updated files from my repository?  The authors here haven't replied to me, so no change has been pulled into this code.  Other than the files I modified, you'll need to download version 1.5.08.204 of the mcMMO.jar file (which was the latest when I made these changes) and put it in ${basedir}/src/main/resources/mcMMO.jar.  That should make your error go away.

**Comment by konnkiti** [comment]
I can not download mcMMO 1.5.08
Could you please modify it to work with the latest version?

**Comment by JakeMoe** [comment]
Hi, I've updated it so it should work with mcMMO v1.5.09-SNAPSHOT.

**Comment by konnkiti** [comment]
I could not build this too.

**Comment by JakeMoe** [comment]
Can you give more info about why you can't build this?  How are you trying to compile it?  What is happening?  What error(s) do you get?  I can't help you with the info you've given me.

**Comment by konnkiti** [comment]
Sorry I forgot to write the log.
C:\Users\konnkiti\mcMMO-WorldGuard-master>mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building mcMMO-WorldGuard 1.0.5
[INFO] ------------------------------------------------------------------------
Downloading: https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/bukkit/bukkit/1.12.1-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://maven.sk89q.com/repo/org/bukkit/bukkit/1.12.1-R0.1-SNAPSHOT/maven-metadata.xml
Downloaded: https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/bukkit/bukkit/1.12.1-R0.1-SNAPSHOT/maven-metadata.xml (1.4 kB at 1.1 kB/s)
Downloading: https://hub.spigotmc.org/nexus/content/repositories/snapshots/com/sk89q/spigot/bukkit-classloader-check/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://maven.sk89q.com/repo/com/sk89q/spigot/bukkit-classloader-check/1.8-R0.1-SNAPSHOT/maven-metadata.xml
Downloaded: http://maven.sk89q.com/repo/com/sk89q/spigot/bukkit-classloader-check/1.8-R0.1-SNAPSHOT/maven-metadata.xml (787 B at 1.3 kB/s)
Downloading: https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/bukkit/bukkit/1.8.6-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://maven.sk89q.com/repo/org/bukkit/bukkit/1.8.6-R0.1-SNAPSHOT/maven-metadata.xml
Downloaded: https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/bukkit/bukkit/1.8.6-R0.1-SNAPSHOT/maven-metadata.xml (1.4 kB at 1.6 kB/s)
Downloading: https://hub.spigotmc.org/nexus/content/repositories/snapshots/com/gmail/nossr50/mcMMO/mcMMO/1.5.08.204/mcMMO-1.5.08.204.pom
Downloading: http://maven.sk89q.com/repo/com/gmail/nossr50/mcMMO/mcMMO/1.5.08.204/mcMMO-1.5.08.204.pom
Downloading: https://repo.maven.apache.org/maven2/com/gmail/nossr50/mcMMO/mcMMO/1.5.08.204/mcMMO-1.5.08.204.pom
[WARNING] The POM for com.gmail.nossr50.mcMMO:mcMMO:jar:1.5.08.204 is missing, no dependency information available
Downloading: https://hub.spigotmc.org/nexus/content/repositories/snapshots/com/gmail/nossr50/mcMMO/mcMMO/1.5.08.204/mcMMO-1.5.08.204.jar
Downloading: http://maven.sk89q.com/repo/com/gmail/nossr50/mcMMO/mcMMO/1.5.08.204/mcMMO-1.5.08.204.jar
Downloading: https://repo.maven.apache.org/maven2/com/gmail/nossr50/mcMMO/mcMMO/1.5.08.204/mcMMO-1.5.08.204.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.324 s
[INFO] Finished at: 2017-11-29T23:33:25+09:00
[INFO] Final Memory: 10M/206M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mcMMO-WorldGuard: Could not resolve dependencies for project org.mcmmo:mcMMO-WorldGuard:jar:1.0.5: Could not find artifact com.gmail.nossr50.mcMMO:mcMMO:jar:1.5.08.204 in spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by JakeMoe** [comment]
That says it's trying to use the old version of mcMMO (1.5.08.204).  You need to re-download the updated sources that point to the new version (v1.5.09-SNAPSHOT), and download and copy the new version into ${basedir}/src/main/resources/mcMMO.jar, then try to compile again.

**Comment by JakeMoe** [comment]
Sorry for the delayed response, this got lost in my inbox.  Yeah, that line would do it; I suppose on my system, it compiled because I still had the old version in my local Maven repo.  I've updated that line, it should compile now.

**Comment by Buzz1971** [comment]
I am all confused minecraft and the plugins all rabbit whole me to death!!
I am trying so frikin hard to setup a server that has specifics such a progressive RPG feel to it 
So I have no experience with coding or atleast minimum amount, can some please contact me so I can go over what I am looking for my server to do please I have tried several places and having absolutely no luck at all with help.

**Comment by t00thpick1** [comment]
@JakeMoe  Would you be interested in maintaining mcMMO-WorldGuard?  I think I can addd you to the repo if you want

**Comment by JakeMoe** [comment]
@t00thpick1 Sorry, I thought I replied to you at the time.  Since I did this, I've left the server this was for, and the server I play on now is Sponge Forge, not Bukkit Vanilla, so I'm coding different things these days.  Again, sorry for the delay, I wasn't intentionally ignoring you.

**Pull request merged**
